#INSTALL FLASK FOR UNIX / LINUX OS #



# use sudo # 

#  sudo apt install python3-venv #

#  CRREAT A VIRTUAL ENVIRONMENT #

# MKDIR MPROJECTS 
# CD MYPROJECTS
# PYTHON3 -M VENV VENV

# INSTALL FLASK FOR WINDOWS #

# OPEN POWERSHELL OR COMMAND PROMPT  PY -3 -M VENV VENVE #

